services:

  backend:
    build:
      context: .
      target: backend
    container_name: ai-wardrobe-backend
    hostname: wardrobebackhost
    expose:
      - "8002"
    env_file:
      - .env
    volumes:
      - ./apps/backend/config:/app/config
      - ./apps/backend/data:/app/data 
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # BACKEND
      - "traefik.http.routers.wardrobe-api.rule=(Host(`wardrobe.traveller-ai.com`) || Host(`www.wardrobe.traveller-ai.com`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.wardrobe-api.entrypoints=websecure"
      - "traefik.http.routers.wardrobe-api.tls.certresolver=le"
      - "traefik.http.services.wardrobe-api.loadbalancer.server.port=8002"

  frontend:
    build:
      context: .
      target: frontend
    container_name: ai-wardrobe-frontend
    hostname: wardrobefronthost
    expose:
      - "3002"
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # FRONTEND
      - "traefik.http.routers.wardrobe-front.rule=Host(`wardrobe.traveller-ai.com`) || Host(`www.wardrobe.traveller-ai.com`)"
      - "traefik.http.routers.wardrobe-front.entrypoints=websecure"
      - "traefik.http.routers.wardrobe-front.tls.certresolver=le"
      - "traefik.http.services.wardrobe-front.loadbalancer.server.port=80"

networks:
  traefik:
    external: true